// <auto-generated />
using EFCoreTablePerTypeInheritance.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreTablePerTypeInheritance.Migrations
{
    [DbContext(typeof(MyApplicationContext))]
    partial class MyApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreTablePerTypeInheritance.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EFCoreTablePerTypeInheritance.Models.Car", b =>
                {
                    b.HasBaseType("EFCoreTablePerTypeInheritance.Models.Vehicle");

                    b.Property<int>("TrunkSize")
                        .HasColumnType("int");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("EFCoreTablePerTypeInheritance.Models.Motorcycle", b =>
                {
                    b.HasBaseType("EFCoreTablePerTypeInheritance.Models.Vehicle");

                    b.Property<int>("EnginePower")
                        .HasColumnType("int");

                    b.ToTable("Motorcycles");
                });

            modelBuilder.Entity("EFCoreTablePerTypeInheritance.Models.Car", b =>
                {
                    b.HasOne("EFCoreTablePerTypeInheritance.Models.Vehicle", null)
                        .WithOne()
                        .HasForeignKey("EFCoreTablePerTypeInheritance.Models.Car", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFCoreTablePerTypeInheritance.Models.Motorcycle", b =>
                {
                    b.HasOne("EFCoreTablePerTypeInheritance.Models.Vehicle", null)
                        .WithOne()
                        .HasForeignKey("EFCoreTablePerTypeInheritance.Models.Motorcycle", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
